# Generated by Django 2.1 on 2018-09-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=256)),
                ('pw', models.CharField(max_length=1024)),
                ('contents', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
