# Generated by Django 2.1 on 2018-09-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenApp', '0002_auto_20180903_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='id',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='uid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
