# Generated by Django 2.1 on 2018-09-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenApp', '0004_auto_20180903_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='some',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
