# Generated by Django 2.1 on 2018-09-03 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokenApp', '0005_myuser_some'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='some',
        ),
    ]
